### ISSUE TITLE
Conda installation not working correctly

### ISSUE THREAD

**Issue by ajakupov** [chartbeat-labs/textacy#127]
Hello. 
I'm currently trying to install textacy via pip and via conda as well.
When installing via pip I get the following error:

```
Exception:
Traceback (most recent call last):
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 31: invalid start byte
```

Must have been an error with s.decode(sys.__stdout__.encoding), but I am not sure.

When trying to install via conda (conda install -c conda-forge textacy) everythinng looks fine but the package is unusable : just a simple function call generates an error:

`doc = textacy.Doc(intial_text)`

returning:

`AttributeError: module 'textacy' has no attribute 'Doc'`

Thank you in advance

**Comment by bdewilde** [comment]
Hi @ajakupov , I've never seen `pip` itself throw an error like that. How strange. Unless there's more to the exception message, though, I don't see how/where `textacy` is involved. I can't replicate it with a fresh install in macOS, and the appveyor build also appears successful on Windows. Can you `pip install` other packages without error?

As for conda... I'm not actually the maintainer of that code. Maybe @rmax would know about this?

**Comment by rmax** [comment]
I've seen an error like that when the underlying exception has an error in a different encoding than the console.  The unreleased version of pip improves this, see https://github.com/pypa/pip/pull/4486 

@ajakupov Try executing `set PYTHONIOENCODING=<your console encoding>` where `<your console encoding>` is `latin1` or any other encoding you use, then run the `pip install` command. 

Could you show the output of `conda install -c conda-forge textacy`?

The conda recipe doesn't provide 32-bits packages and it seems you are using a 32-bits system.  Or at least your python runtime seems to be 32-bits.

Just in case, do you have a `textacy.py` file in your directory?

**Comment by ajakupov** [comment]
Hi, @rmax, @bdewilde Thank you for your response. Just running pip install textacy from conda command prompt (I'm using miniConda) solved the problem (after uninstalling the textacy of course). It is remarkable that 'conda install -c conda-forge textacy' command installs 0.3.4 version and not 0.4.1. So everything is alright, but I still wonder if there is still a possibility to install textacy withoud conda (I suppose the problem lies in the fact that there are some important library dependencies not installed, like Numpy or SciPy). I still should give a try all the solutions you have proposed to finally figure out what the initial problem is))). However, till now everything seems to be working fine, but only under Conda shell.

**Comment by ajakupov** [comment]
Wow, after setting encoding to latin1 it returns 
  Running setup.py install for cytoolz ... error
Exception:
Traceback (most recent call last):
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 40: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\ajakupov\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 40: invalid continuation byte
