### ISSUE TITLE
Issue while creating and loading large corpus

### ISSUE THREAD

**Issue by ranka47** [chartbeat-labs/textacy#67]
I have 1.7*10^8 sentences, each of length 5. My RAM is of size 8GB. 
It is consuming a lot of RAM while creating the corpus. 
Also suppose in case if I take around 850000 sentences only then it saves successfully but while loading back I get the following error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/textacy/corpus.py", line 268, in load
    for spacy_doc, metadata in zip(spacy_docs, metadata_stream):
  File "/usr/local/lib/python2.7/dist-packages/textacy/fileio/read.py", line 173, in read_spacy_docs
    yield SpacyDoc(spacy_vocab).from_bytes(bytes_string)
  File "spacy/tokens/doc.pyx", line 615, in spacy.tokens.doc.Doc.from_bytes (spacy/tokens/doc.cpp:12347)
  File "spacy/serialize/packer.pyx", line 132, in spacy.serialize.packer.Packer.unpack_into (spacy/serialize/packer.cpp:6349)
  File "spacy/serialize/huffman.pyx", line 107, in spacy.serialize.huffman.HuffmanCodec.decode (spacy/serialize/huffman.cpp:3548)
Exception: Buffer exhausted at 4/6 symbols read.

```
## Steps to Reproduce (for bugs)

I am working over the [text8](http://mattmahoney.net/dc/text8). I have to do the Named Entity Recognition. 
1. First I broke the corpus into sentences of window_width = 5. 
1. Then I am taking each sentence as a doc and creating a corpus. 

## Your Environment

* `textacy` and `spacy` versions: 0.3.3 and 1.6.0
* Python version: 2.7.12
* Operating system and version: Ubuntu 16.04; 4.4.0-64-generic

**Comment by bdewilde** [comment]
Hi @ranka47 , sorry about the trouble. The current implementation of `textacy.Corpus` reads _all_ of the data into memory at once, so you may simply be running out of RAM. You might consider streaming each document in one at a time, processing it, and aggregating the results. I've wanted to implement a streaming corpus for a while, but haven't had the bandwidth — PRs welcome :wink:!

As for the exception: That's a problem in `spacy`'s serializer, and you should definitely post that as an issue on their repo: https://github.com/explosion/spaCy/issues
