### ISSUE TITLE
textacy.Doc.load(content, lang="en") does not handle less common utf-8 characters well

### ISSUE THREAD

**Issue by GruffPrys** [chartbeat-labs/textacy#81]
I have English texts that contains utf-8 characters such as "ŷ" and "ŵ" from Welsh named entities:

`problem_text = "paying tribute to the work of the Tŷ Gwyn Education Centre"`

Loading a saved textacy Doc that contains these characters fails with a SpaCy assertion error:

`doc = textacy.Doc.load("", name="problem_text_doc")`

```
Traceback (most recent call last):
  File "C:\textacy_test.py", line 19, in <module>
    doc = doc.load("member_docs/", name=str(member_id))
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\textacy\doc.py", line 232, in load
    return cls(list(fileio.read_spacy_docs(spacy_vocab, docs_fname))[0],
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\textacy\fileio\read.py", line 173, in read_spacy_docs
    yield SpacyDoc(spacy_vocab).from_bytes(bytes_string)
  File "spacy/tokens/doc.pyx", line 613, in spacy.tokens.doc.Doc.from_bytes (spacy/tokens/doc.cpp:12323)
  File "spacy/serialize/packer.pyx", line 129, in spacy.serialize.packer.Packer.unpack_into (spacy/serialize/packer.cpp:6258)
  File "spacy/serialize/packer.pyx", line 195, in spacy.serialize.packer.Packer._char_decode (spacy/serialize/packer.cpp:7791)
  File "spacy/tokens/doc.pyx", line 459, in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:10057)
AssertionError
```

A workaround is to instantiate a Textacy Doc with utf-8 text as content before loading the 'real' content. For example, the code below will successfully load `problem_text_doc`:

```
doc = textacy.Doc("ŷ", lang="en")
doc = textacy.Doc.load("", name="problem_text_doc")
```

However, it would be better if setting the character set when loading was made more explicit or that utf-8 characters were enabled by default as it took me quite a while to track down what was causing the assertion error.

Thanks for Textacy - it's great! :)

**Comment by GruffPrys** [comment]
Hmm... after playing around some more, the workaround doesn't work in other cases, so I have no idea what's going on. Adding some text with a 'ŵ' fails, for example:

`problem_text = "paying tribute to the work of the Tŷ Gwyn Education Centre and Dŵr Cymru"`

I'm going to remove the accents from the texts for the time being, but this will likely be a problem for me in the future.

**Comment by bdewilde** [comment]
Hi @GruffPrys , sorry about the trouble. This looks to be an issue with spacy's serializer, so I recommend posting it to the [spacy issues page](https://github.com/explosion/spaCy/issues). That said, I've definitely seen issues like this before: [this one](https://github.com/explosion/spaCy/issues/927), for example.

I may be able to help debug, but would definitely need a full code sample that reproduces the problem as well as info about your dev environment, including versions of spacy and textacy. Your best bet, though, is definitely reaching out on spacy's repo.

**Comment by GruffPrys** [comment]
Hi @bdewilde, thanks for the speedy reply.

I agree that it seems to be the same issue that you link to on the spacy issues page, and apologies for assuming it was to do with Textacy. I'll try and add to the issue on spacy's repo, but for completeness, and because I'm not familiar yet with doing this with Spacy without Textacy holding my hands, here's a minimal code sample that fails:   

First:
```
import textacy
doc = textacy.Doc("paying tribute to the work of the Tŷ Gwyn Education Centre", lang="en")
doc.save("", name="problem_text")
```
then:
```
import textacy
doc = textacy.Doc.load("", name="problem_text")
```

This gives:

```
Traceback (most recent call last):
  File "C:\textacy_test.py", line 19, in <module>
    doc = doc.load("member_docs/", name=str(member_id))
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\textacy\doc.py", line 232, in load
    return cls(list(fileio.read_spacy_docs(spacy_vocab, docs_fname))[0],
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\textacy\fileio\read.py", line 173, in read_spacy_docs
    yield SpacyDoc(spacy_vocab).from_bytes(bytes_string)
  File "spacy/tokens/doc.pyx", line 613, in spacy.tokens.doc.Doc.from_bytes (spacy/tokens/doc.cpp:12323)
  File "spacy/serialize/packer.pyx", line 129, in spacy.serialize.packer.Packer.unpack_into (spacy/serialize/packer.cpp:6258)
  File "spacy/serialize/packer.pyx", line 195, in spacy.serialize.packer.Packer._char_decode (spacy/serialize/packer.cpp:7791)
  File "spacy/tokens/doc.pyx", line 459, in spacy.tokens.doc.Doc.push_back (spacy/tokens/doc.cpp:10057)
AssertionError
```

Note that running all the above code as part of the same script works:
```
import textacy
doc = textacy.Doc("paying tribute to the work of the Tŷ Gwyn Education Centre", lang="en")
doc.save("", name="problem_text")
doc = textacy.Doc.load("", name="problem_text")
```
```
>>> Doc(11 tokens; "paying tribute to the work of the Tŷ Gwyn Educa...")
```

System: Surface Book i5 8Gb RAM, Win 10, Python 3.5, Visual Studio 2015, Spacy 1.7.1, Textacy 0.3.0

**Comment by GruffPrys** [comment]
I've just realized I get a different possibly more useful error message with this alternative text string:

```
import textacy
doc = textacy.Doc("tŷ means house in Welsh", lang="en")
doc.save("", name="problem_text")
```
then:
```
import textacy
doc = textacy.Doc.load("", name="problem_text")
```

This produces:

```
Traceback (most recent call last):
  File "C:\textacy_error_minimal_example_load.py", line 2, in <module>
    doc = textacy.Doc.load("", name="problem_text")
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\textacy\doc.py", line 232, in load
    return cls(list(fileio.read_spacy_docs(spacy_vocab, docs_fname))[0],
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\textacy\fileio\read.py", line 173, in read_spacy_docs
    yield SpacyDoc(spacy_vocab).from_bytes(bytes_string)
  File "spacy/tokens/doc.pyx", line 613, in spacy.tokens.doc.Doc.from_bytes (spacy/tokens/doc.cpp:12323)
  File "spacy/serialize/packer.pyx", line 132, in spacy.serialize.packer.Packer.unpack_into (spacy/serialize/packer.cpp:6388)
  File "spacy/serialize/huffman.pyx", line 107, in spacy.serialize.huffman.HuffmanCodec.decode (spacy/serialize/huffman.cpp:3548)
Exception: Buffer exhausted at 4/5 symbols read.

```

**Comment by GruffPrys** [comment]
The other accented character unique to Welsh and not supported until Utf-8 is 'ŵ'.

I added it to the string:

```
# coding: utf-8
import textacy
doc = textacy.Doc("tŷ is house in Welsh and dŵr is water", lang="en")
doc.save("", name="problem_text")
doc = textacy.Doc.load("", name="problem_text")
print (doc)
```
Result:

`Doc(9 tokens; "tŷ is house in Welsh and dŵr is water")`

BUT:

```
import textacy
doc = textacy.Doc.load("", name="problem_text")
```

Result:

`Doc(9 tokens; "tŰ arhouse in Welsh and dŵr is water ")`

**Comment by bdewilde** [comment]
Hi @GruffPrys, a thousand apologies for the late response. For what it's worth, spacy v2's de/serialization is totally different than v1's, and now so is the current version of textacy on `master`. (Will publish a proper release soon.) `Doc`s are now saved and loaded as pickle files, and I did not run into the issue you reported above:

```
>>> import textacy
>>> doc = textacy.Doc("tŷ is house in Welsh and dŵr is water", lang="en")
>>> doc.save("/Users/burtondewilde/Desktop/problem_text.pkl")
>>> doc = textacy.Doc.load("/Users/burtondewilde/Desktop/problem_text.pkl")
>>> print(doc)
Doc(9 tokens; "tŷ is house in Welsh and dŵr is water")
```

I'm going to close this out, but don't hesitate to re-open if the current version of textacy isn't working on your side.

**Comment by GruffPrys** [comment]
Thanks @bdewilde.  I realized the bug was on spaCy's side of things so I worked around it, but I'm really looking forward to playing with the latest version of Textacy. It makes things a lot more convenient! Keep up the good work :)
